FROM node:23-alpine AS build

WORKDIR /app

COPY . /app/

RUN yarn install && yarn build


FROM node:23-alpine 

WORKDIR /app

RUN yarn global add serve

COPY --from=build /app/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]

